default_language_version:
  python: "3.13"
default_install_hook_types:
  - pre-push
default_stages:
  - pre-push

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
- repo: local
  hooks:
  - id: ruff-check
    name: ruff check
    entry: bash -c 'uv run ruff check .'
    language: system
    types: [python]
  - id: ruff-format-check
    name: ruff format check
    entry: bash -c 'uv run ruff format --check .'
    language: system
    types: [python]
  - id: unittests
    name: Python unit tests
    entry: bash -c 'uv run -m unittest discover -s tests'
    language: system