version: 1
disable_existing_loggers: False
formatters:
  colored:
    '()': 'colorlog.ColoredFormatter'
    format: "%(blue)s%(name)-5s%(reset)s | %(log_color)s%(levelname)-8s%(reset)s | %(cyan)s%(asctime)s%(reset)s | %(message_log_color)s%(message)s | %(yellow)s%(filename)s > %(funcName)s%(reset)s"
    log_colors:
      DEBUG: 'cyan'
      INFO: 'green'
      WARNING: 'yellow'
      ERROR: 'red'
      CRITICAL: 'bold_white,bg_red'
    secondary_log_colors:
      message:
        ERROR: 'bold_red'
        CRITICAL: 'bold_red'
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5

loggers:
  app:
    level: DEBUG
    handlers: [console, file]
    propagate: False

root:
  level: INFO
  handlers: [console]
